# Generated by Django 6.0.3 on 2026-04-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company_number', models.CharField(max_length=100, unique=True)),
                ('tax_number', models.CharField(max_length=100, unique=True)),
                ('company_type', models.CharField(choices=[('LOCAL', 'Local'), ('MULTINATIONAL', 'Multinational')], default='LOCAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('total_imports', models.PositiveIntegerField(default=0)),
                ('total_unfinished_imports', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('MEDICAL', 'Medical'), ('ELECTRONICS', 'Electronics'), ('FOOD', 'Food'), ('CHEMICAL', 'Chemical'), ('CONSTRUCTION', 'Construction'), ('AUTOMOTIVE', 'Automotive'), ('TEXTILE', 'Textile'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired')], default='VALID', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='trade_management.company')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-issued_date'],
            },
        ),
    ]
