# Generated by Django 5.1.5 on 2026-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
