# Generated by Django 5.1.5 on 2026-04-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management', '0003_importpermit_importinspection_importdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='Bank IBAN'),
        ),
    ]
