# Generated by Django 5.1.5 on 2026-04-13 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_management', '0004_company_bank_iban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'System Admin'), ('COMPANY_OWNER', 'Company Owner'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('TAX_OFFICER', 'Tax Authority Officer'), ('ANTI_CORRUPTION', 'Anti-Corruption Authority'), ('LICENSE_REGULATOR', 'License Regulator'), ('TRADE_MINISTRY', 'Trade Ministry'), ('VIEWER', 'Read-only Viewer')], default='COMPANY_OWNER', max_length=25)),
                ('authority_type', models.CharField(choices=[('NONE', 'Not Applicable'), ('CUSTOMS_AUTHORITY', 'Libyan Customs Authority'), ('TAX_AUTHORITY', 'Tax Authority'), ('ANTI_CORRUPTION_AUTH', 'Anti-Corruption Authority'), ('LICENSE_AUTHORITY', 'License & Registration Authority'), ('TRADE_MINISTRY', 'Ministry of Trade & Economy'), ('CENTRAL_BANK', 'Central Bank of Libya')], default='NONE', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
